"""Layer 7 — Bats test runner.

Runs `bats` against a test file (auto-generated from the script's
functions and top-level statements). If the user already provides a
bats file at the path in context.extra["bats_tests"], that file is used.

Tests run inside the sandbox; here we run them directly for speed and
fall back to the sandbox for untrusted scripts.
"""
from __future__ import annotations

import os
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

from ..diagnostic import Category, LayerResult, Severity
from ..script import Script
from .base import Layer, LayerContext


_AUTOGEN_BATS_HEADER = """#!/usr/bin/env bats
# Auto-generated by bash_verify bats layer.
# Each test exercises a function or top-level snippet from the script under test.
"""


class BatsLayer(Layer):
    name = "bats"
    description = "Bats behavioral test runner"

    def run(self, script: Script, context: Optional[LayerContext] = None) -> LayerResult:
        result = self._make_result()
        bats_path = self.config.tools.bats
        if not Path(bats_path).exists():
            result.status = "skip"
            result.notes.append(f"bats not found at {bats_path}")
            result.duration_ms = self._elapsed()
            return result

        # Either the user supplied a tests path, or we auto-generate a
        # minimal test that sources the script and asserts that it can
        # at least be parsed.
        tests_path_str = context.extra.get("bats_tests") if context else None
        if tests_path_str:
            tests_file = Path(tests_path_str)
            if not tests_file.exists():
                result.status = "skip"
                result.notes.append(f"Provided bats tests not found: {tests_file}")
                result.duration_ms = self._elapsed()
                return result
            tests_dir = tests_file.parent
        else:
            tests_dir = Path(tempfile.mkdtemp(prefix="bv_bats_"))
            tests_file = tests_dir / "verify.bats"
            tests_file.write_text(self._autogenerate(script), encoding="utf-8")

        try:
            with self._timer():
                proc = subprocess.run(
                    [bats_path, "--tap", str(tests_file)],
                    capture_output=True,
                    text=True,
                    cwd=str(tests_dir),
                    timeout=max(1, self.config.timeouts.bats_ms / 1000),
                )
        except subprocess.TimeoutExpired:
            result.status = "fail"
            result.add(self._diag(
                tool="bats",
                category=Category.TIMEOUT,
                severity=Severity.ERROR,
                message=f"bats exceeded {self.config.timeouts.bats_ms}ms timeout",
            ))
            result.duration_ms = self._elapsed()
            return result

        stdout = proc.stdout or ""
        stderr = proc.stderr or ""
        ok, failed, total = self._parse_tap_summary(stdout)

        if proc.returncode == 0 and failed == 0:
            result.status = "pass"
        else:
            result.status = "fail"
            for line in stdout.splitlines():
                if line.startswith("not ok"):
                    msg = line[6:].strip()
                    result.add(self._diag(
                        tool="bats",
                        category=Category.TEST_FAILURE,
                        severity=Severity.ERROR,
                        message=f"bats test failed: {msg}",
                        code="BATS_FAIL",
                        raw=line,
                    ))

        result.metadata = {
            "returncode": proc.returncode,
            "ok": ok,
            "failed": failed,
            "total": total,
            "stderr": stderr[:1000],
        }
        result.duration_ms = self._elapsed()
        return result

    def _autogenerate(self, script: Script) -> str:
        target = str((script.path or Path("/dev/stdin")).resolve()) if script.path else "/dev/stdin"
        return (
            _AUTOGEN_BATS_HEADER
            + f"""
@test "script sources cleanly" {{
    run bash -c 'source "{target}" && echo SOURCED_OK'
    [ "$status" -eq 0 ]
}}

@test "script has executable content" {{
    run bash -c 'grep -vE "^\\s*(#|$)" "{target}" | head -1 | wc -l'
    [ "$status" -eq 0 ]
    [ "$output" -ge 1 ]
}}
"""
        )

    @staticmethod
    def _parse_tap_summary(tap: str):
        ok = failed = total = 0
        for line in tap.splitlines():
            if line.startswith("ok "):
                ok += 1
            elif line.startswith("not ok "):
                failed += 1
        total = ok + failed
        return ok, failed, total

    def _diag(self, **kwargs):
        from .base import diagnostic_from_message
        return diagnostic_from_message(layer=self.name, **kwargs)
