"""Layer 7 — Bats test runner.

Runs `bats` against a test file (auto-generated from the script's
functions and top-level statements). If the user already provides a
bats file at the path in context.extra["bats_tests"], that file is used.

Tests run inside the sandbox; here we run them directly for speed and
fall back to the sandbox for untrusted scripts.
"""
from __future__ import annotations

import base64
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

from ..diagnostic import Category, LayerResult, Severity
from ..script import Script
from .base import Layer, LayerContext


_AUTOGEN_BATS_HEADER = """#!/usr/bin/env bats
# Auto-generated by bash_verify bats layer.
# Each test exercises a function or top-level snippet from the script under test.
"""


class BatsLayer(Layer):
    name = "bats"
    description = "Bats behavioral test runner"

    def run(self, script: Script, context: Optional[LayerContext] = None) -> LayerResult:
        result = self._make_result()
        bats_path = self.config.tools.bats
        if not Path(bats_path).exists():
            # P0 8: a missing bats is INCOMPLETE, not skip.
            result.status = "incomplete"
            result.notes.append(f"bats not found at {bats_path}")
            result.duration_ms = self._elapsed()
            return result

        # P0 1: bats must run INSIDE the sandbox, not on the host.
        # The previous implementation ran `bats` on the host and
        # the auto-generated bats test did `source "{target}"` on
        # the host. That sourced untrusted code on the host. Now we:
        #   1. Stage the bats test file (or auto-generated content) in
        #      a temp dir
        #   2. Stage the target script content (NOT a host path) into
        #      the same dir
        #   3. Run `bats <testfile>` entirely inside the sandbox
        tests_path_str = context.extra.get("bats_tests") if context else None
        if tests_path_str:
            tests_file = Path(tests_path_str)
            if not tests_file.exists():
                result.status = "incomplete"
                result.notes.append(f"Provided bats tests not found: {tests_file}")
                result.duration_ms = self._elapsed()
                return result
        else:
            tests_file = Path(tempfile.mkdtemp(prefix="bv_bats_")) / "verify.bats"
            tests_file.write_text(self._autogenerate(script), encoding="utf-8")

        # Stage the target script content into a sibling file. The bats
        # test sources THIS file, not a host path. The content is the
        # SHA256-bound bytes from the Script.
        target_staged = tests_file.parent / "target.sh"
        target_staged.write_text(script.content, encoding="utf-8")

        # P0 1: bats must run inside the sandbox. We stage the bats
        # test file AND the target script inside a single tar, push
        # it into the container, then run bats there. The host's bats
        # binary is NOT invoked.
        try:
            with self._timer():
                from ..sandbox.docker_sandbox import DockerSandbox
                sb = DockerSandbox(self.config)
                # Build a wrapper script that runs bats on the staged
                # test file. Bats is installed in the sandbox image
                # (bash:5.1 may not have bats; the layer will skip
                # INCOMPLETE if bats is missing in the image, which
                # is the correct P0 8 behavior).
                # P0-2 (round 2): use base64 to stage arbitrary source.
                # Base64 is shell-safe ([A-Za-z0-9+/=]) and avoids
                # any parser collision with the target's content.
                # The marker is a random hex string (no chance of
                # appearing in user content).
                wrapper = "#!/usr/bin/env bash\n"
                wrapper += "set -u\n"
                wrapper += "cd /work || exit 1\n"
                wrapper += "command -v bats >/dev/null 2>&1 || "
                wrapper += "{ echo BATS_MISSING_IN_SANDBOX; exit 1; }\n"
                target_b64 = base64.b64encode(
                    script.content.encode("utf-8", errors="replace")
                ).decode("ascii")
                wrapper += f"base64 -d > /work/target.sh <<'BV_B64_46FC252E5A654665'\n"
                wrapper += target_b64 + "\n"
                wrapper += f"BV_B64_46FC252E5A654665\n"
                bats_content = tests_file.read_text(encoding="utf-8")
                bats_b64 = base64.b64encode(
                    bats_content.encode("utf-8", errors="replace")
                ).decode("ascii")
                wrapper += f"base64 -d > /work/verify.bats <<'BV_B64_46FC252E5A654665'\n"
                wrapper += bats_b64 + "\n"
                wrapper += f"BV_B64_46FC252E5A654665\n"
                wrapper += "bats --tap /work/verify.bats\n"
                with sb.run_script(wrapper) as sr:
                    proc_stdout = sr.stdout
                    proc_stderr = sr.stderr
                    proc_returncode = sr.exit_code
                    proc_timed_out = sr.timed_out
        except Exception as e:
            result.status = "fail"
            result.add(self._diag(
                tool="bats",
                category=Category.RUNTIME,
                severity=Severity.ERROR,
                message=f"bats sandbox execution failed: {e!r}",
            ))
            result.duration_ms = self._elapsed()
            return result

        stdout = proc_stdout or ""
        stderr = proc_stderr or ""
        ok, failed, total = self._parse_tap_summary(stdout)

        # P1 bats: a non-zero return with empty TAP output means bats could
        # not produce test results at all — most commonly because bats is
        # not installed in the sandbox image (the wrapper emits the
        # `BATS_MISSING_IN_SANDBOX` sentinel), but it also covers any
        # other environment problem where the sandbox produced no TAP.
        # That is NOT a test failure: tests did not run. Surface it as
        # `incomplete` with an INFO diagnostic so the operator sees
        # the reason instead of a contradictory `fail` with zero
        # diagnostics.
        bats_missing_sentinel = "BATS_MISSING_IN_SANDBOX" in stdout
        env_no_tap = (proc_returncode != 0 and total == 0)
        if bats_missing_sentinel or env_no_tap:
            if bats_missing_sentinel:
                reason = (
                    "bats is not installed in the sandbox image; "
                    "behavioral tests skipped"
                )
                diag_code = "BATS_MISSING_IN_SANDBOX"
                reason_key = "bats_not_installed_in_sandbox"
            else:
                reason = (
                    "bats produced no TAP output (non-zero returncode "
                    "with empty TAP indicates an environment problem, "
                    "not a test failure); behavioral tests skipped"
                )
                diag_code = "BATS_NO_TAP"
                reason_key = "no_tap_output"
            result.status = "incomplete"
            result.add(self._diag(
                tool="bats",
                category=Category.DEPENDENCY,
                severity=Severity.INFO,
                message=reason,
                code=diag_code,
            ))
            result.metadata = {
                "returncode": proc_returncode,
                "ok": ok,
                "failed": failed,
                "total": total,
                "stderr": stderr[:1000],
                "incomplete_reason": reason_key,
            }
            result.duration_ms = self._elapsed()
            return result

        if proc_returncode == 0 and failed == 0 and not proc_timed_out:
            result.status = "pass"
        else:
            result.status = "fail"
            for line in stdout.splitlines():
                if line.startswith("not ok"):
                    msg = line[6:].strip()
                    result.add(self._diag(
                        tool="bats",
                        category=Category.TEST_FAILURE,
                        severity=Severity.ERROR,
                        message=f"bats test failed: {msg}",
                        code="BATS_FAIL",
                        raw=line,
                    ))

        result.metadata = {
            "returncode": proc_returncode,
            "ok": ok,
            "failed": failed,
            "total": total,
            "stderr": stderr[:1000],
        }
        result.duration_ms = self._elapsed()
        return result

    def _autogenerate(self, script: Script) -> str:
        # P0 1: the bats test must NEVER reference a host path. It
        # sources the staged ./target.sh, which is staged into the
        # sandbox next to the bats test file.
        return (
            _AUTOGEN_BATS_HEADER
            + """

@test "script sources cleanly" {
    run bash -c 'source "./target.sh" && echo SOURCED_OK'
    [ "$status" -eq 0 ]
}

@test "script has executable content" {
    run bash -c 'grep -vE "^\\s*(#|$)" "./target.sh" | head -1 | wc -l'
    [ "$status" -eq 0 ]
    [ "$output" -ge 1 ]
}
"""
        )

    @staticmethod
    def _parse_tap_summary(tap: str):
        ok = failed = total = 0
        for line in tap.splitlines():
            if line.startswith("ok "):
                ok += 1
            elif line.startswith("not ok "):
                failed += 1
        total = ok + failed
        return ok, failed, total

    def _diag(self, **kwargs):
        from .base import diagnostic_from_message
        return diagnostic_from_message(layer=self.name, **kwargs)
